### PR TITLE
Fail when you send a message to an entity type that wasn't registered…

### LINKED ISSUE #28: Fail when you send a message to an entity type that wasn't registered
See logic in `Sharding` when we access `entityStates`, currently we just do nothing when the entity type is not found. An error would be better.

### PR DESCRIPTION
**Pull request by altostraus**
Closes #28

### CODE REVIEW

**Comment by altostraus** [comment]
simply Fail with Exception when no entity type was found.

**Comment by ghostdogpr** [comment]
Looks good! How about this error message instead: "Entity type X was not registered".

**Comment by ghostdogpr** [comment]
Would you mind also making a PR for the 1.x branch too? Trying to keep them in sync for now.

**Comment by altostraus** [comment]
sure.

**Comment by ghostdogpr** [comment]
Thanks!

**Pull request merged**
